author: zhu
spring:
  profiles:
    active: dev
  activiti:
    check-process-definitions: false #自动检查、部署流程定义文件
    database-schema-update: true #自动更新数据库结构
    process-definition-location-prefix: classpath:static/bpmn/ #流程定义文件存放目录
    history-level: audit #保留任务历史的级别
