author: zhu

spring:
  profiles:
    active: dev
  activiti:
    database-schema-update: true #自动更新数据库结构
    process-definition-location-prefix: classpath:static/bpmn/ #bpmn文件存放存放目录
    check-process-definitions: false #不自动检查、部署流程定义文件
    history-level: audit #保留任务历史的级别
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mybatis/**/*.xml
  type-aliases-package: com.**.bean
