#端口号
version: v1.0.0.DEV
server:
  port: 8082

spring:
  activiti:
    check-process-definitions: false
    database-schema-update: true

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://192.168.81.250/act?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall
    use-global-data-source-stat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL

mybatis:
  mapper-locations: classpath:mybatis/**/*.xml
  type-aliases-package: com.**.bean
  configuration:
    use-generated-keys: true #新增数据后自动获取数据库自增主键, 需要使用 keyProperty 指定主键
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #这个是可以打印sql、参数、查询结果的

logging:
  level:
    com.z.act.core.security.mapper: debug

sys-default:
  admin-role:
  -
    role-name: 超级管理员
  -
    role-name: SUPER_ADMIN
  admin-user:
  -
    user-name: admin
    user-alias: 超管
    user-pwd: admin
  - user-name: root
    user-alias: root
    user-pwd: root
  test-role:
  -
    role-name: NORMAL
  test-user:
  -
    user-name: zim
    user-alias: 普通人
    user-pwd: zim
  - user-name: test
    user-alias: 测试用户
    user-pwd: test