version: v1.0.0.DEV
server:
  port: 8081
  #servlet:
    #context-path: /activiti/

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://192.168.81.250/act?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: Hikari-zim

mybatis:
  mapper-locations: classpath:mybatis/**/*.xml
  type-aliases-package: com.zhu.**.bean

redis:
  max-total: 10
  max-idle: 10
  min-idle: 0
  redis-list:
    -
      host: 192.168.5.120
      port: 6379
      auth: admin

sys-default:
  admin-role:
    -
      role-name: 超级管理员
    -
      role-name: SUPER_ADMIN
  admin-user:
    -
      user-name: admin
      user-alias: 超管
      user-pwd: admin
    - user-name: root
      user-alias: root
      user-pwd: root
  test-role:
    -
      role-name: NORMAL
  test-user:
    -
      user-name: zim
      user-alias: 普通人
      user-pwd: zim
    - user-name: test
      user-alias: 测试用户
      user-pwd: test